### ISSUE TITLE
enetcache does not respect global cache_period

### ISSUE THREAD

**Issue by ffh-webadmin** [lolli42/enetcache#6] opened 2020-01-10 10:51 UTC
setCachePageLifetime() has a small bug. If a page has no cache_timeout (=0), Typo3 will use the global cache ttl defined via TS in config.cache_period. 

But the function will ignore this value and set the ttl of the page to the lifetime of enetcache, which could be to long. 

Example: 
config.cache_period = 60
Page TTL = 0
EnetCache TTL = 1800

This will result in a TTL of 1800 for the whole page instead of 60.

Fix:

> if (!$GLOBALS['TSFE']->page['cache_timeout']) {
                // No cache timeout was set yet.
                // This would cause min to always return 0 so we filter it out.
                $GLOBALS['TSFE']->page['cache_timeout'] = min($lifetime, $GLOBALS['TSFE']->config['config']['cache_period']);
             }

$GLOBALS['TSFE']->config['config']['cache_period'] is added to the if()

**Comment by lolli42** [comment] 2021-02-12 14:33
Thx! I refactored the method slightly and hope the issue is fixed now.

**Closed** 2021-02-12 14:33 UTC
